CREATE TABLE inbound_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_number VARCHAR(50) NOT NULL,
    received_at     TIMESTAMPTZ NOT NULL
);

CREATE TABLE inbound_order_line (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbound_order_id BIGINT  NOT NULL REFERENCES inbound_order (id),
    item_id          BIGINT  NOT NULL REFERENCES item (id),
    quantity         INTEGER NOT NULL CHECK (quantity > 0)
);

CREATE TABLE outbound_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number VARCHAR(50) NOT NULL,
    ordered_at      TIMESTAMPTZ NOT NULL,
    status          VARCHAR(20) NOT NULL CHECK (status IN ('OPEN', 'FULFILLED', 'CANCELLED'))
);

CREATE TABLE outbound_order_line (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbound_order_id  BIGINT  NOT NULL REFERENCES outbound_order (id),
    item_id            BIGINT  NOT NULL REFERENCES item (id),
    requested_quantity INTEGER NOT NULL CHECK (requested_quantity > 0),
    fulfilled_quantity INTEGER NOT NULL DEFAULT 0
        CHECK (fulfilled_quantity >= 0 AND fulfilled_quantity <= requested_quantity)
);

CREATE TABLE stock_adjustment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjusted_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE stock_adjustment_line (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_adjustment_id BIGINT       NOT NULL REFERENCES stock_adjustment (id),
    item_id             BIGINT       NOT NULL REFERENCES item (id),
    reason              VARCHAR(100) NOT NULL,
    quantity            INTEGER      NOT NULL CHECK (quantity <> 0)
);