spring.application.name=inventory-service
spring.datasource.url=${DB_URL:jdbc:postgresql://host.docker.internal:5432/inventory}
spring.datasource.username=${DB_USERNAME:inventory}
spring.datasource.password=${DB_PASSWORD:inventory}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false